warhorse:
  general:
    op_number: "000-000"
    user_tag: 'user'
    ttl: '2023-12-12' #Kill Date
    ntp_timezone: 'Etc/Universal' # Time Zone Link
    vault_key: 'vault_key'
    # snapshots: true
  backup: 
    backup_bucket_name: "backup-bucket"
    backup_bucket_region: "us-east-1"
    backup_bucket_endpoint: "https://nyc3.digitaloceanspaces.com"
    backup_bucket_access_key: "access_key"
    backup_bucket_secret_key: "secret_key"
  vpn: # Optional
    tailscale:
      tailnet_name: 'tailnet.github'
      tailscale_auth_key: "tskey-auth-0000000"
      enable_hostnames: true
  notification: # Optional
    email:
      host: "smtp.sendgrid.net"
      from: "noreply@mydomain.com"
      port: 587
      username: "apikey"
      password: "password"
  dns:
    provider: "digitalocean"
    op_tld: 'mydomain.com' # Reasorce Domain
    op_domain_name: 'operation.mydomain.com'
  vm:
    - name: "teamserver"
      provider: "digitalocean"
      http_proxy: "none"
      firewall:
        enabled: true
      golang:
        enabled: true
      mythic:
        enabled: true
        username: 'admin'
        password: "nrwgkgh23rje31trfg" # CHANGEME
        operation: "default"
        auth_header_name: "cdnauth" # CHANGEME
        auth_header_value: "{{ 'gdshe2r23' | b64encode }}" # CHANGEME
        cdn: # Redirector
        - name: "azure1"
          provider: "azure"
          hostname: "azcdn1" # CHANGE ME
          redirect_url: "https://azure.microsoft.com"
        - name: "aws"
          provider: "aws"
          redirect_url: "https://aws.com"

  terraform:
    state_bucket_enabled: true
    state_bucket_name: "tfstate-bucket"
    state_bucket_region: "us-east-1"
    state_bucket_endpoint: "https://nyc3.digitaloceanspaces.com"
    bucket_access_key: "access_key" # {{ lookup('community.general.bitwarden_secrets_manager'), 'bucket_access_key' }}
    bucket_secret_key: "secret_key"
    digitalocean_token: "token"
    aws_profile: "profile_name"

  users:
    - username: ralph
      name: Ralph
      authorized_keys:
      - "{{ lookup('file', '/Users/ralph/.ssh/id_rsa.pub') }}"
      shell: '/usr/bin/zsh'
      email: ralph@mydomain.com
    # - username: Extra
    #   name: Extra
    #   authorized_keys:
    #   - "{{ lookup('file', '/Users/Extra/.ssh/id_rsa.pub') }}"
    #   shell: '/usr/bin/zsh'
    #   email: Extra@mydomain.com
